version: "3.9"
services:
  clock:
    build: .
    command: python clock.py
    volumes:
      - .:/app
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - VACCINE_CHECK_INTERVAL=60
      - ENABLE_HYVEE=true
      - HYVEE_RADIUS=20
      - HYVEE_LATITUDE=39.1040382
      - HYVEE_LONGITUDE=-94.5701803
      - NOTIFY_SLACK=true
      - SLACK_TAG_CHANNEL=false
    env_file:
      - .env
  redis:
    image: "redis:alpine"
